"""
output_module/response_models.py
---------------------------------
Typed dataclasses for the Output Module (Module 4) of the TDDR pipeline.

    LegalEvidence       – one matched regulation citation with source excerpt
    FinalSystemResponse – complete, traceable system output ready for API / UI
"""

from __future__ import annotations

import json
from dataclasses import dataclass, field, asdict
from typing import List, Optional


EXCERPT_MAX_CHARS = 300


@dataclass
class LegalEvidence:
    """
    A single piece of legal evidence matched from a retrieved regulation chunk.

    Parameters
    ----------
    regulation    : Short regulation name, e.g. ``"SWM_RULES"``, ``"IPC"``.
    version       : Version / edition string, e.g. ``"2016"``.
    section       : Section identifier cited by the LLM, e.g. ``"Rule 5"``.
    effective_from: ISO-8601 date string when this version became effective.
    effective_to  : ISO-8601 date string when superseded, or ``None`` (current).
    excerpt       : Short text excerpt from the matching chunk (≤ 300 chars).
    source_file   : Original source file path if available, else ``None``.
    """

    regulation: str
    version: str
    section: str
    effective_from: str
    effective_to: Optional[str]
    excerpt: str
    source_file: Optional[str] = None

    def to_dict(self) -> dict:
        return {
            "regulation":    self.regulation,
            "version":       self.version,
            "section":       self.section,
            "effective_from": self.effective_from,
            "effective_to":  self.effective_to,
            "excerpt":       self.excerpt,
            "source_file":   self.source_file,
        }

    def __repr__(self) -> str:
        return (
            f"LegalEvidence(regulation={self.regulation!r}, "
            f"version={self.version!r}, "
            f"section={self.section!r})"
        )


@dataclass
class FinalSystemResponse:
    """
    The complete, structured output of the TDDR pipeline.

    This is what the Output Module (Module 4) returns to the API / UI /
    report generator.  Every field is serialisable to JSON.

    Parameters
    ----------
    answer      : Human-readable answer generated by Module 3.
    confidence  : LLM confidence level — ``"high"``, ``"medium"``, or ``"low"``.
    explanation : Reasoning / legal basis explanation from the LLM.
    legal_basis : List of ``LegalEvidence`` objects resolved from citations.
    metadata    : Operational metadata dict (model, chunk count, timestamp…).
    """

    answer:      str
    confidence:  str                    # "high" | "medium" | "low"
    explanation: str
    legal_basis: List[LegalEvidence]    = field(default_factory=list)
    metadata:    dict                   = field(default_factory=dict)

    # ---- serialisation -------------------------------------------------

    def to_dict(self) -> dict:
        return {
            "answer":      self.answer,
            "confidence":  self.confidence,
            "explanation": self.explanation,
            "legal_basis": [e.to_dict() for e in self.legal_basis],
            "metadata":    self.metadata,
        }

    def to_json(self, indent: int = 2) -> str:
        return json.dumps(self.to_dict(), indent=indent)

    def __repr__(self) -> str:
        return (
            f"FinalSystemResponse(confidence={self.confidence!r}, "
            f"legal_basis_count={len(self.legal_basis)}, "
            f"model={self.metadata.get('model_used', '?')!r})"
        )
